# Generated by Django 4.1.1 on 2022-11-10 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller_app', '0006_alter_reseller_s_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
