# Generated by Django 4.1.1 on 2022-11-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller_app', '0007_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_category',
            field=models.CharField(default='', max_length=40),
        ),
    ]
